apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: expense
  name: expense
spec:
  replicas: {{ .values.expense.replicas }}
  selector:
    matchLabels:
      app: expense
  template:
    metadata:
      labels:
        app: expense
    spec:
      containers:
        - image: {{ .values.expense.image }}
          imagePullPolicy: {{ .values.expense.imagePullPolicy }}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: DB_HOST
              value: "mysql.default.svc.cluster.local"
            - name: DB_USER
              value: "budgetbook"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-password
            - name: DB_NAME
              value: "budgetbook"
            - name: DB_PORT
              value: "3306"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: budgetbook
                  key: JWT_SECRET
          name: expense
          ports:
            - containerPort: {{  .values.expense.port }}
              protocol: TCP
      restartPolicy: {{ .values.expense.restartPolicy }}
